import { Navbar } from '@/components/Navbar'
import './globals.css'
import { FormProvider } from '@/context/FormProvider'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alzhaimer Web App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <FormProvider>
        {children}
        </FormProvider>
      </body>
    </html>
  )
}
